"""Offline-calibrated constants for the issue 0021 Pre-CMD Hook.

Generated by scripts/calibrate_hook.py.
"""

from __future__ import annotations

V1_REPLAY_NAME_ORDER: tuple[str, ...] = (
    "oracle_write",
    "oracle_compression",
    "verbatim_event_oracle",
    "oracle_retrieval",
    "injection_oracle",
    "evidence_given_reasoning",
    "oracle_route",
    "oracle_granularity",
    "graph_off",
    "safety_off",
)

TOP_K: int = 5
FALLBACK_THRESHOLD: float = 0.0

RPE_JUDGE_WEIGHTS: tuple[float, ...] = (0.1191125317, 0.3437922836, -0.2246797519, -0.7677289859, 0.838383277, 0.3463999211, 0.0386442298, 0.0290499693, 0.1138335586, 0.0743814422, 0.0740640732, -0.2535824256, 0.6398615301, -0.3767372129, -0.3767372129, -0.3767372129)
RPE_JUDGE_INTERCEPT: float = -0.4199589498
