"""CMD-Audit V0 standalone harness."""

from .attribution import AttributionResult, assign_attribution
from .baselines import (
    BaselineSuiteResult,
    SubagentJudgeMonitorDecision,
    run_baseline_suite,
    validate_evidence_pointers,
    validate_monitor_payload,
)
from .harness import (
    AuditResult,
    FullAuditResult,
    diagnosis_predictions,
    run_case,
    run_case_full,
    run_cases,
    run_cases_full,
    write_comparison_metrics_table,
    write_repair_success_table_from_full,
)
from .writers import (
    REPLAY_TABLE_ORDER,
    write_attribution_table,
    write_confusion_matrix_table,
    write_csv_table,
    write_post_repair_table,
    write_retrieval_metrics_table,
    write_retrieval_trace_table,
    write_text_artifact,
)
from .failure_memory import (
    FailureMemoryRecord,
    FailureMemoryStore,
    RecurrenceComparisonRow,
    RecurrenceSummary,
    build_failure_memory_context,
    compute_recurrence_summary,
    run_recurrence_comparison,
    run_recurrence_comparisons,
    write_recurrence_comparison_table,
)
from .labels import (
    MONITOR_ANOMALY_REASON_VALUES,
    V0_PIPELINE_LABEL_ORDER,
    V0_PIPELINE_LABELS,
    MonitorAnomalyReasonError,
    validate_monitor_anomaly_reason,
    validate_v0_label,
)
from .metrics import DiagnosisMetrics, DiagnosisPrediction, compute_diagnosis_metrics
from .models import ProbeCase, load_probe_cases
from .post_repair import (
    ECSDraft,
    PostRepairResult,
    RepairedContext,
    build_repaired_context,
    classify_repair_assessment,
    draft_ecs,
    run_hard_case_update_baseline,
    run_post_repair_context_replay,
    validate_sandbox_path,
)
from .repairs import (
    RepairClaimLedger,
    RepairComparisonRow,
    TargetedRepairAction,
    build_repair_claim_ledger,
    compute_repair_success_summary,
    get_targeted_repair_action,
    make_repair_comparison,
    write_repair_success_table,
)
from .replays import ReplayResult, run_v0_replay_portfolio
from .retrieval_baselines import (
    RankedRetrievalTrace,
    RetrievalBaselineResult,
    RetrievalBaselineSuiteResult,
    RetrievalMetrics,
    compute_evidence_boundary_audit,
    compute_retrieval_metrics,
    enforce_retrieval_error_boundary,
    run_bm25_retrieval,
    run_hybrid_rerank_retrieval,
    run_retrieval_baseline_suite,
)
from .version_gates import (
    GateCriterion,
    GateResult,
    GateReview,
    check_v0_to_v1_gate,
    check_v1_to_v2_gate,
    write_gate_review,
    write_gate_status,
)

__all__ = [
    "AttributionResult",
    "AuditResult",
    "BaselineSuiteResult",
    "DiagnosisMetrics",
    "DiagnosisPrediction",
    "ECSDraft",
    "FailureMemoryRecord",
    "FailureMemoryStore",
    "FullAuditResult",
    "GateCriterion",
    "GateResult",
    "GateReview",
    "MONITOR_ANOMALY_REASON_VALUES",
    "MonitorAnomalyReasonError",
    "PostRepairResult",
    "ProbeCase",
    "RankedRetrievalTrace",
    "REPLAY_TABLE_ORDER",
    "RepairClaimLedger",
    "RepairComparisonRow",
    "ReplayResult",
    "RepairedContext",
    "RetrievalBaselineResult",
    "RetrievalBaselineSuiteResult",
    "RetrievalMetrics",
    "RecurrenceComparisonRow",
    "RecurrenceSummary",
    "SubagentJudgeMonitorDecision",
    "TargetedRepairAction",
    "V0_PIPELINE_LABEL_ORDER",
    "V0_PIPELINE_LABELS",
    "assign_attribution",
    "build_failure_memory_context",
    "check_v0_to_v1_gate",
    "check_v1_to_v2_gate",
    "build_repair_claim_ledger",
    "build_repaired_context",
    "classify_repair_assessment",
    "compute_diagnosis_metrics",
    "compute_evidence_boundary_audit",
    "compute_recurrence_summary",
    "compute_repair_success_summary",
    "compute_retrieval_metrics",
    "diagnosis_predictions",
    "draft_ecs",
    "enforce_retrieval_error_boundary",
    "get_targeted_repair_action",
    "load_probe_cases",
    "make_repair_comparison",
    "run_baseline_suite",
    "run_bm25_retrieval",
    "run_case",
    "run_case_full",
    "run_cases",
    "run_cases_full",
    "run_hard_case_update_baseline",
    "run_hybrid_rerank_retrieval",
    "run_recurrence_comparison",
    "run_recurrence_comparisons",
    "run_post_repair_context_replay",
    "run_retrieval_baseline_suite",
    "run_v0_replay_portfolio",
    "validate_evidence_pointers",
    "validate_monitor_anomaly_reason",
    "validate_monitor_payload",
    "validate_sandbox_path",
    "validate_v0_label",
    "write_attribution_table",
    "write_comparison_metrics_table",
    "write_confusion_matrix_table",
    "write_csv_table",
    "write_gate_review",
    "write_gate_status",
    "write_post_repair_table",
    "write_recurrence_comparison_table",
    "write_repair_success_table",
    "write_repair_success_table_from_full",
    "write_retrieval_metrics_table",
    "write_retrieval_trace_table",
    "write_text_artifact",
]
